name: Push to GitLab

on:
  push:
    branches:
      - main  # Change to your default branch name

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Information
        run: |
          echo "GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}"
          echo "Current branch: ${{ github.ref }}"

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          # Set up Git user information
          git config --global user.email "your_email@example.com"
          git config --global user.name "Your Name"

          # Check if we can add the remote
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gl.sihirbox.com/175883/kick_track.git || {
            echo "Failed to add GitLab remote"
            git remote -v  # Print the remotes for debugging
            exit 1
          }

          # Push to the GitLab repository
          git push gitlab main  # Change 'main' to your branch name if different
