name: Push to GitLab

on:
  push:
    branches:
      - main  # Change to your default branch name

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git config --global user.email "mis93@mis.prangroup.com"
          git config --global user.name "Md. Salauddin"
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gl.sihirbox.com/175883/kick_track.git 
          git push gitlab main  # Change to your branch name
